#ifndef SFML_SIMPLE_WRAPPER_AUDIO_SF_PLAYBACK_DEVICE_NOTIFICATION_H
#define SFML_SIMPLE_WRAPPER_AUDIO_SF_PLAYBACK_DEVICE_NOTIFICATION_H


#ifdef __cplusplus
extern "C" {
#endif


// Playback device has been started
#define SFML_SIMPLE_WRAPPER_sf_PlaybackDevice_Notification_DeviceStarted 0

// Playback device has been stopped
#define SFML_SIMPLE_WRAPPER_sf_PlaybackDevice_Notification_DeviceStopped 1

// Playback device has been rerouted (Generated on platforms that support automatic stream routing)
#define SFML_SIMPLE_WRAPPER_sf_PlaybackDevice_Notification_DeviceRerouted 2

// Playback device interruption has begun (Generated on Apple mobile platforms)
#define SFML_SIMPLE_WRAPPER_sf_PlaybackDevice_Notification_DeviceInterruptionBegan 3

// Playback device interruption has ended (Generated on Apple mobile platforms)
#define SFML_SIMPLE_WRAPPER_sf_PlaybackDevice_Notification_DeviceInterruptionEnded 4

// Playback device has been unlocked (Generated by Emscripten/WebAudio)
#define SFML_SIMPLE_WRAPPER_sf_PlaybackDevice_Notification_DeviceUnlocked 5


#ifdef __cplusplus
}
#endif


#endif
